### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [theemaraud3r/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques and kept your code well organized. Take a look at the issues I created for some best practice tweaks as well as some efficiency techniques that will save you sometime later on. Here is a good article with some examples on best practice: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by theemaraud3r** [comment]
thanks for in input ill start using class more than id, iv also read through that article now.
